[build]
  publish = "C:\Users\CYNTHIA J\OneDrive\Desktop\wed\AfricanecityBankLoan"
  command = "python manage.py collectstatic --noinput"

[build.environment]
  DJANGO_SETTINGS_MODULE = "AfricanecityBankLoan.settings"

[build.processing]
  # process all HTML files to update relative links
  # (useful when Django is hosted at a subpath)
  # see https://docs.netlify.com/configure-builds/file-based-configuration/#processing
  '*.html' = [
    { command = 'python', args = ['C:\Users\CYNTHIA J\OneDrive\Desktop\wed\AfricanecityBankLoan\manage.py', 'process_html', '-o', '.', '{path}'] }
  ]
